server:
  port: 1111

spring:
  profiles:
    group:
      studyPurposes:
        - "testH2"
        - "mysqldb"
    active: testH2

spring-doc:
  pathsToMatch: /**/**
#  swagger-ui:
#    use-root-path: true
